from datetime import date, timedelta

WEEK_DATA = {
    4: {
        "size": "a poppy seed",
        "length": "0.04 in",
        "weight": "<1 gram",
        "developing": ["neural tube forming", "heart cells beginning to flicker"],
        "baby_can": ["implant into the uterine wall"],
        "fun_fact": "I'm tinier than a grain of rice but my heart cells are already starting to pulse!",
        "mom_might_feel": ["fatigue", "breast tenderness", "missed period"],
        "baby_voice_hints": ["I just got here!", "everything is brand new", "so tiny but here"],
    },
    5: {
        "size": "a sesame seed",
        "length": "0.05 in",
        "weight": "<1 gram",
        "developing": ["heart starting to beat", "brain dividing into sections", "arm and leg buds forming"],
        "baby_can": ["have a heartbeat!"],
        "fun_fact": "My heart just started beating! It's so fast, like a tiny hummingbird.",
        "mom_might_feel": ["morning sickness starting", "fatigue", "frequent urination"],
        "baby_voice_hints": ["my heart is beating!", "can you believe it", "I'm growing so fast"],
    },
    6: {
        "size": "a lentil",
        "length": "0.25 in",
        "weight": "<1 gram",
        "developing": ["nose, mouth, and ears forming", "intestines developing", "brain growing rapidly"],
        "baby_can": ["move (but you can't feel it yet!)"],
        "fun_fact": "I'm starting to get a face! Little dots where my eyes will be.",
        "mom_might_feel": ["morning sickness", "mood swings", "bloating"],
        "baby_voice_hints": ["getting my face together", "literally growing a brain over here"],
    },
    7: {
        "size": "a blueberry",
        "length": "0.5 in",
        "weight": "<1 gram",
        "developing": ["arms and legs lengthening", "liver producing red blood cells", "appendix and pancreas forming"],
        "baby_can": ["generate brain cells at 100 per minute"],
        "fun_fact": "My brain is making 100 new cells every single minute. I'm thinking... about you!",
        "mom_might_feel": ["nausea", "food aversions", "excess saliva"],
        "baby_voice_hints": ["my brain is buzzing", "I'm a blueberry!", "growing arms!"],
    },
    8: {
        "size": "a kidney bean",
        "length": "0.63 in",
        "weight": "1 gram",
        "developing": ["fingers and toes forming", "upper lip and nose taking shape", "eyelids forming"],
        "baby_can": ["wiggle tiny limb buds"],
        "fun_fact": "I'm getting fingers! Tiny little nubs that will one day hold yours.",
        "mom_might_feel": ["nausea peaking", "heightened sense of smell", "fatigue"],
        "baby_voice_hints": ["look, fingers!", "I'll hold your hand someday", "still so tiny"],
    },
    9: {
        "size": "a grape",
        "length": "0.9 in",
        "weight": "2 grams",
        "developing": ["muscles forming", "heart finishing dividing into 4 chambers", "teeth buds appearing"],
        "baby_can": ["make tiny movements", "have a four-chambered heart"],
        "fun_fact": "My heart just got all four chambers! A real heart, beating for you.",
        "mom_might_feel": ["mood swings", "waist thickening", "nasal congestion"],
        "baby_voice_hints": ["my heart is complete now", "I'm a grape-sized miracle"],
    },
    10: {
        "size": "a kumquat",
        "length": "1.2 in",
        "weight": "4 grams",
        "developing": ["bones and cartilage forming", "kidneys producing urine", "tooth buds developing"],
        "baby_can": ["bend arms at the elbow", "swallow fluid"],
        "fun_fact": "I can bend my arms now! Practicing my tiny stretches in here.",
        "mom_might_feel": ["round ligament twinges", "visible veins", "growing belly"],
        "baby_voice_hints": ["doing my stretches", "double digits baby!", "getting strong"],
    },
    11: {
        "size": "a fig",
        "length": "1.6 in",
        "weight": "7 grams",
        "developing": ["tooth buds continuing", "hair follicles forming", "nail beds developing"],
        "baby_can": ["open and close fists", "hiccup"],
        "fun_fact": "I just learned to make a fist! Don't worry, I'm friendly.",
        "mom_might_feel": ["less nausea (hopefully!)", "skin changes", "increased energy"],
        "baby_voice_hints": ["making fists", "hiccupping in here", "getting feisty"],
    },
    12: {
        "size": "a lime",
        "length": "2.1 in",
        "weight": "14 grams",
        "developing": ["vocal cords forming", "intestines moving into abdomen", "reflexes developing"],
        "baby_can": ["make facial expressions", "suck thumb", "respond to stimulation"],
        "fun_fact": "I can make faces now! Practicing my smile for the day I meet you.",
        "mom_might_feel": ["nausea easing", "increased appetite", "first trimester ending!"],
        "baby_voice_hints": ["first trimester done!", "practicing my smile", "I'm a lime!"],
    },
    13: {
        "size": "a peach",
        "length": "2.9 in",
        "weight": "23 grams",
        "developing": ["fingerprints forming", "organs maturing", "vocal cords complete"],
        "baby_can": ["produce urine", "move fluidly"],
        "fun_fact": "I'm getting my own fingerprints! Nobody in the world will have ones like mine.",
        "mom_might_feel": ["energy returning", "second trimester beginning", "less nausea"],
        "baby_voice_hints": ["welcome to trimester two!", "one of a kind fingerprints", "unique already"],
    },
    14: {
        "size": "a lemon",
        "length": "3.4 in",
        "weight": "1.5 oz",
        "developing": ["roof of mouth forming", "hormones being produced", "facial muscles working"],
        "baby_can": ["squint", "frown", "grimace", "suck thumb"],
        "fun_fact": "I can squint and make faces! Mostly I just look confused in here.",
        "mom_might_feel": ["more energy", "round ligament pain", "growing belly visible"],
        "baby_voice_hints": ["making silly faces", "feeling expressive today", "lemon-sized!"],
    },
    15: {
        "size": "an apple",
        "length": "4 in",
        "weight": "2.5 oz",
        "developing": ["skeleton hardening from cartilage to bone", "taste buds forming", "eyebrows growing"],
        "baby_can": ["sense light through eyelids", "hiccup regularly"],
        "fun_fact": "I can taste what you eat through the amniotic fluid! Share something yummy!",
        "mom_might_feel": ["nasal congestion", "increased blood flow", "skin glow starting"],
        "baby_voice_hints": ["I can taste things!", "what are you eating?", "growing eyebrows"],
    },
    16: {
        "size": "an avocado",
        "length": "4.6 in",
        "weight": "3.5 oz",
        "developing": ["circulatory system fully functional", "eyes moving slowly", "toenails growing"],
        "baby_can": ["hold head more erect", "make coordinated movements"],
        "fun_fact": "My heart is pumping about 25 quarts of blood a day! Working hard in here.",
        "mom_might_feel": ["backaches starting", "feeling baby movement soon", "glowing skin"],
        "baby_voice_hints": ["avocado vibes", "heart is pumping strong", "you might feel me soon!"],
    },
    17: {
        "size": "a turnip",
        "length": "5.1 in",
        "weight": "5.9 oz",
        "developing": ["fat stores beginning", "sweat glands forming", "umbilical cord strengthening"],
        "baby_can": ["practice breathing movements", "yawn"],
        "fun_fact": "I just learned to yawn! Life in here is cozy but busy.",
        "mom_might_feel": ["increased appetite", "vivid dreams", "stretch marks appearing"],
        "baby_voice_hints": ["yawning a lot", "getting chubby", "so cozy in here"],
    },
    18: {
        "size": "a bell pepper",
        "length": "5.6 in",
        "weight": "6.7 oz",
        "developing": ["ears moving to final position", "myelin coating nerves", "digestive system active"],
        "baby_can": ["hear sounds!", "yawn and hiccup"],
        "fun_fact": "I can hear rumbling and whooshing sounds! Your heartbeat is my favorite song.",
        "mom_might_feel": ["feeling first kicks (quickening!)", "dizziness", "leg cramps"],
        "baby_voice_hints": ["I hear your heartbeat!", "your voice is muffled but lovely", "kick kick!"],
    },
    19: {
        "size": "a mango",
        "length": "6 in",
        "weight": "8.5 oz",
        "developing": ["vernix caseosa coating forming", "sensory development accelerating", "arms and legs proportional"],
        "baby_can": ["hear external sounds", "develop unique sleep patterns"],
        "fun_fact": "I'm getting a waxy coating called vernix to protect my skin. Spa day every day!",
        "mom_might_feel": ["hip pain", "skin changes", "feeling movement regularly"],
        "baby_voice_hints": ["spa treatment in here", "I can hear music!", "halfway almost!"],
    },
    20: {
        "size": "a banana",
        "length": "6.5 in",
        "weight": "10.2 oz",
        "developing": ["vernix coating fully formed", "taste buds mature", "gulping amniotic fluid"],
        "baby_can": ["hear your voice clearly", "swallow", "suck thumb"],
        "fun_fact": "I can hear your voice now! When you talk, I recognize it. Keep talking to me, mama.",
        "mom_might_feel": ["halfway there!", "feeling strong kicks", "belly button changes"],
        "baby_voice_hints": ["HALFWAY!", "I know your voice!", "keep talking to me"],
    },
    21: {
        "size": "a carrot",
        "length": "10.5 in",
        "weight": "12.7 oz",
        "developing": ["eyebrows and eyelids fully formed", "bone marrow making blood cells", "movements more coordinated"],
        "baby_can": ["do somersaults", "grip things", "taste sweet vs savory"],
        "fun_fact": "I'm doing flips in here! Gymnast in training. Watch out, Olympics!",
        "mom_might_feel": ["Braxton Hicks starting", "stretch marks", "increased appetite"],
        "baby_voice_hints": ["doing gymnastics!", "I prefer sweet things", "somersault champion"],
    },
    22: {
        "size": "a papaya",
        "length": "10.9 in",
        "weight": "15.2 oz",
        "developing": ["eyes formed but iris has no color yet", "pancreas maturing", "lips becoming distinct"],
        "baby_can": ["perceive light and dark", "have regular sleep/wake cycles"],
        "fun_fact": "I have lips now! Getting ready for my first kiss on your cheek.",
        "mom_might_feel": ["linea nigra appearing", "swollen feet", "increased vaginal discharge"],
        "baby_voice_hints": ["got my lips ready", "sleeping and waking on a schedule", "what color are my eyes?"],
    },
    23: {
        "size": "a grapefruit",
        "length": "11.4 in",
        "weight": "1.1 lb",
        "developing": ["skin becoming less translucent", "lungs preparing for breathing", "hearing improving daily"],
        "baby_can": ["hear loud noises from outside", "feel your movements"],
        "fun_fact": "I can hear music now! Play me something good. I'm forming my taste already.",
        "mom_might_feel": ["swollen ankles", "backaches", "practice contractions"],
        "baby_voice_hints": ["play me music!", "over a pound now!", "I feel when you move"],
    },
    24: {
        "size": "an ear of corn",
        "length": "11.8 in",
        "weight": "1.3 lb",
        "developing": ["lungs developing branches", "skin becoming opaque", "inner ear fully developed"],
        "baby_can": ["have a sense of balance", "respond to your voice"],
        "fun_fact": "I have balance now! I know which way is up. Well, mostly.",
        "mom_might_feel": ["glucose screening time", "Braxton Hicks", "trouble sleeping"],
        "baby_voice_hints": ["I know which way is up!", "viability milestone!", "getting balanced"],
    },
    25: {
        "size": "a cauliflower",
        "length": "13.6 in",
        "weight": "1.5 lb",
        "developing": ["baby fat filling out wrinkly skin", "nostrils opening", "nervous system maturing"],
        "baby_can": ["respond to familiar voices", "grasp with hands"],
        "fun_fact": "My nostrils are opening! I'm practicing breathing in the fluid. No air yet, but soon!",
        "mom_might_feel": ["heartburn", "constipation", "hemorrhoids"],
        "baby_voice_hints": ["practicing breathing", "getting chubbier", "I know your voice anywhere"],
    },
    26: {
        "size": "a head of lettuce",
        "length": "14 in",
        "weight": "1.7 lb",
        "developing": ["eyes opening for first time", "brain wave activity increasing", "air sacs in lungs forming"],
        "baby_can": ["open eyes!", "blink", "see light through your belly"],
        "fun_fact": "I just opened my eyes for the first time! Everything's blurry but beautiful.",
        "mom_might_feel": ["trouble sleeping", "pelvic pressure", "swelling"],
        "baby_voice_hints": ["I can SEE!", "everything's new", "opened my eyes today"],
    },
    27: {
        "size": "a head of broccoli",
        "length": "14.4 in",
        "weight": "1.9 lb",
        "developing": ["lungs and nervous system maturing", "regular sleep cycles", "brain very active"],
        "baby_can": ["dream (REM sleep!)", "recognize your voice specifically", "hiccup rhythmically"],
        "fun_fact": "I started dreaming! I wonder what I dream about... probably you.",
        "mom_might_feel": ["third trimester beginning!", "shortness of breath", "leg cramps"],
        "baby_voice_hints": ["third trimester!", "I dream now", "I think I dream about your voice"],
    },
    28: {
        "size": "an eggplant",
        "length": "14.8 in",
        "weight": "2.2 lb",
        "developing": ["eyebrows and eyelashes visible", "brain developing grooves", "body fat increasing"],
        "baby_can": ["blink", "dream", "regulate body temperature slightly"],
        "fun_fact": "I have eyelashes! Gonna bat them at you the second we meet.",
        "mom_might_feel": ["kick counts important now", "Braxton Hicks more frequent", "nesting urge"],
        "baby_voice_hints": ["got my eyelashes", "fluttering my eyes", "2 pounds strong!"],
    },
    29: {
        "size": "a butternut squash",
        "length": "15.2 in",
        "weight": "2.5 lb",
        "developing": ["muscles and lungs maturing", "head growing for brain development", "bones fully developed but soft"],
        "baby_can": ["kick forcefully", "stretch", "make grabbing motions"],
        "fun_fact": "My kicks are getting stronger! Sorry if I wake you up. I'm just excited!",
        "mom_might_feel": ["frequent urination returning", "heartburn", "difficulty breathing"],
        "baby_voice_hints": ["KICK!", "sorry not sorry", "getting strong in here"],
    },
    30: {
        "size": "a cabbage",
        "length": "15.7 in",
        "weight": "2.9 lb",
        "developing": ["red blood cell production shifts to bone marrow", "lanugo hair disappearing", "fat layers adding quickly"],
        "baby_can": ["grasp firmly", "track light", "breathe rhythmically (practice)"],
        "fun_fact": "I'm losing my fuzzy body hair and gaining real baby fat! Getting cute for you.",
        "mom_might_feel": ["fatigue returning", "mood swings", "frequent Braxton Hicks"],
        "baby_voice_hints": ["10 weeks to go!", "getting camera-ready", "almost 3 pounds!"],
    },
    31: {
        "size": "a coconut",
        "length": "16.2 in",
        "weight": "3.3 lb",
        "developing": ["brain connections forming rapidly", "irises can react to light", "lungs continuing to mature"],
        "baby_can": ["turn head side to side", "process all five senses", "have sleep cycles"],
        "fun_fact": "All five of my senses are working! I can taste, hear, see light, feel, and even smell.",
        "mom_might_feel": ["leaking colostrum", "back pain", "shortness of breath"],
        "baby_voice_hints": ["all five senses online!", "I can feel everything", "getting so aware"],
    },
    32: {
        "size": "a squash",
        "length": "16.7 in",
        "weight": "3.7 lb",
        "developing": ["toenails and fingernails fully formed", "skin becoming soft and smooth", "practicing breathing more"],
        "baby_can": ["have definite sleep/wake patterns you can notice", "suck strongly"],
        "fun_fact": "I have real fingernails now! Might need my first manicure when I come out.",
        "mom_might_feel": ["heartburn intensifying", "pelvic pressure", "nesting instinct strong"],
        "baby_voice_hints": ["got my nails done", "sleeping on a schedule now", "8 months!"],
    },
    33: {
        "size": "a pineapple",
        "length": "17.2 in",
        "weight": "4.2 lb",
        "developing": ["bones hardening (except skull for delivery)", "immune system developing", "amniotic fluid at peak volume"],
        "baby_can": ["detect light", "coordinate breathing and swallowing", "dream vivid dreams"],
        "fun_fact": "My skull bones are staying soft on purpose so I can fit through! Smart, right?",
        "mom_might_feel": ["difficulty sleeping", "frequent urination", "Braxton Hicks increasing"],
        "baby_voice_hints": ["big brain moves", "over 4 pounds!", "getting ready"],
    },
    34: {
        "size": "a cantaloupe",
        "length": "17.7 in",
        "weight": "4.7 lb",
        "developing": ["central nervous system maturing", "lungs nearly mature", "fat accumulating for warmth"],
        "baby_can": ["recognize and prefer your voice over all others", "have firm grip"],
        "fun_fact": "Your voice is my absolute favorite sound in the whole world. Nobody else compares.",
        "mom_might_feel": ["pelvic pain", "fatigue", "vision changes"],
        "baby_voice_hints": ["your voice is my favorite", "almost ready", "getting chubby cheeks"],
    },
    35: {
        "size": "a honeydew melon",
        "length": "18.2 in",
        "weight": "5.3 lb",
        "developing": ["kidneys fully developed", "liver can process waste", "most organs nearly complete"],
        "baby_can": ["have strong reflexes", "respond to light by turning head"],
        "fun_fact": "Almost all my organs are ready! Just doing final quality checks in here.",
        "mom_might_feel": ["frequent urination", "Braxton Hicks", "baby dropping soon"],
        "baby_voice_hints": ["quality control phase", "5 weeks left!", "systems almost ready"],
    },
    36: {
        "size": "a head of romaine lettuce",
        "length": "18.7 in",
        "weight": "5.8 lb",
        "developing": ["vernix coating getting thicker", "gums hardening", "circulation and immune system ready"],
        "baby_can": ["suck and swallow in coordination", "turn toward light"],
        "fun_fact": "I'm considered early term now! I could come any time, but I'm gonna cook a bit more.",
        "mom_might_feel": ["baby dropping (lightening)", "pelvic pressure increasing", "easier breathing"],
        "baby_voice_hints": ["almost done cooking!", "could come any time", "but I'm comfy"],
    },
    37: {
        "size": "a bunch of Swiss chard",
        "length": "19.1 in",
        "weight": "6.3 lb",
        "developing": ["lung surfactant production complete", "firm grasp", "all organs functional"],
        "baby_can": ["breathe on my own if born now", "grasp your finger tightly"],
        "fun_fact": "I'm officially early term! If I came now, I'd be just fine. But let me marinate.",
        "mom_might_feel": ["nesting instinct peak", "mucus plug changes", "cervix softening"],
        "baby_voice_hints": ["full term zone!", "ready but patient", "let me marinate a little more"],
    },
    38: {
        "size": "a leek",
        "length": "19.6 in",
        "weight": "6.8 lb",
        "developing": ["brain and lungs continue maturing", "firm grip for holding your finger", "toenails reach toe tips"],
        "baby_can": ["produce cortisol for breathing outside", "have a firm grip"],
        "fun_fact": "I'm producing a hormone to help my lungs work in the outside air. Getting ready for my first breath!",
        "mom_might_feel": ["Braxton Hicks frequent", "cervical changes", "anxiety and excitement"],
        "baby_voice_hints": ["practicing my first breath", "almost there!", "I can't wait"],
    },
    39: {
        "size": "a small watermelon",
        "length": "20 in",
        "weight": "7.3 lb",
        "developing": ["brain still adding neurons", "chest becoming more prominent", "all systems go"],
        "baby_can": ["flex all limbs", "cry (ready for first cry!)", "breathe independently"],
        "fun_fact": "I'm full term! My bags are packed. Just waiting for the right moment to meet you.",
        "mom_might_feel": ["contractions starting?", "nesting overdrive", "emotional anticipation"],
        "baby_voice_hints": ["full term!", "any day now", "I'm ready to see your face"],
    },
    40: {
        "size": "a watermelon",
        "length": "20.2 in",
        "weight": "7.6 lb",
        "developing": ["continuing to build fat stores", "brain development continues", "antibodies from you via placenta"],
        "baby_can": ["everything needed for the outside world"],
        "fun_fact": "Due date! I might come today, or I might make you wait. But I promise I'm coming, mama.",
        "mom_might_feel": ["contractions (real ones!)", "excitement and anxiety", "so ready"],
        "baby_voice_hints": ["due date!", "I'm coming!", "see you so soon mama"],
    },
    41: {
        "size": "a watermelon",
        "length": "20.4 in",
        "weight": "7.9 lb",
        "developing": ["still growing and gaining weight", "nails might be long", "still perfectly healthy"],
        "baby_can": ["everything — just taking my time!"],
        "fun_fact": "I know I'm a little late. I just wasn't done being close to you yet.",
        "mom_might_feel": ["impatience", "monitoring appointments", "ready to meet baby"],
        "baby_voice_hints": ["fashionably late", "savoring our time", "almost ready, I promise"],
    },
    42: {
        "size": "a watermelon",
        "length": "20.5 in",
        "weight": "8.1 lb",
        "developing": ["fully developed", "vernix mostly absorbed", "ready for the world"],
        "baby_can": ["everything — truly ready!"],
        "fun_fact": "Okay okay, I'm coming! I just loved being this close to your heart.",
        "mom_might_feel": ["likely being induced", "excitement", "nervousness"],
        "baby_voice_hints": ["okay I'm really coming now", "loved being close to your heart", "HERE I COME"],
    },
}


def get_current_week(due_date: date) -> int:
    """Calculate current pregnancy week from due date (40 weeks gestation)."""
    conception_approx = due_date - timedelta(weeks=40)
    weeks_pregnant = (date.today() - conception_approx).days // 7
    return max(4, min(42, weeks_pregnant))


def get_week_info(week: int) -> dict:
    """Return data for the given week, with fallback to nearest available."""
    if week in WEEK_DATA:
        return WEEK_DATA[week]
    nearest = min(WEEK_DATA.keys(), key=lambda k: abs(k - week))
    return WEEK_DATA[nearest]


def get_trimester(week: int) -> str:
    if week <= 13:
        return "first"
    elif week <= 26:
        return "second"
    else:
        return "third"


def weeks_remaining(due_date: date) -> int:
    days = (due_date - date.today()).days
    return max(0, days // 7)
